apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-config
  namespace: targeting-service-prd
data:
  PORT: "8003"
  POSTGRES_USER: "fiapadmin"
  DATABASE_URL: "postgresql://fiapadmin:IK5bKDl9lJh2joyHnO32MKlb9Gd0y@ppsql-targeting-togglemaster.postgres.database.azure.com/targeting_db?sslmode=require"
  AUTH_SERVICE_URL: "http://auth.132.196.214.124.nip.io"