apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-config
  namespace: targeting-service-prd
data:
  PORT: "8003"
  POSTGRES_USER: "adminuser"
  DATABASE_URL: "postgresql://adminuser:T0ggl3M%40ster2026!@pg-targeting-togglemaster-fase4.postgres.database.azure.com/targeting_db?sslmode=require"
  AUTH_DATABASE_URL: "postgresql://adminuser:T0ggl3M%40ster2026!@pg-auth-togglemaster-fase4.postgres.database.azure.com:5432/auth_db?sslmode=require"
  AUTH_SERVICE_URL: "http://auth-service.auth-service-prd.svc.cluster.local:80"