apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting-service-prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: targeting-service
          image: toggleacrfase4.azurecr.io/targeting-service:9c062b2
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: targeting-config
            - secretRef:
                name: targeting-secrets
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "targeting-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production,service.namespace=togglemaster"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "targeting-service"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_TRACE_DEBUG
              value: "false"
            - name: DD_TRACE_OTEL_ENABLED
              value: "false"
