apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting-service-prd
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: http


#kubectl run -it --rm curl --image=curlimages/curl -n targeting-service-prd --restart=Never -- curl http://targeting-service.targeting-service-prd.svc.cluster.local:8003/health
