apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation-service-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
        prometheus.io/path: "/metrics"
      labels:
        app: evaluation-service
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: evaluation-service
          image: toggleacrfase4.azurecr.io/evaluation-service:00b9e34
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: evaluation-config
            - secretRef:
                name: evaluation-secrets
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "evaluation-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production,service.namespace=togglemaster"
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "evaluation-service"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_TRACE_OTEL_ENABLED
              value: "false"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
