apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation-service-prd
type: Opaque
stringData:
  REDIS_URL: "rediss://:FNFHRTqmzjhpRrCHIQBN8pfrWD9ZhPWlyAzCaB6E6sg=@redis-togglemaster.redis.cache.windows.net:6380"
  SERVICE_API_KEY: "tm_key_e61a9bd085e898e4f3c2cefd4e3b297fd78b76a297f0b766d597e8aa691bb1df"
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=satogglemaster;AccountKey=DVjnc2ICnm0MODd+HMRTKI43PZyza937hYbs2t7N9ox0IY5RQ+VkABpRLfcsNhtY7pUSUrAS3yjh+AStxPYBUw==;EndpointSuffix=core.windows.net"