apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation-service-prd
type: Opaque
stringData:
  REDIS_PASSWORD: "FNFHRTqmzjhpRrCHIQBN8pfrWD9ZhPWlyAzCaB6E6sg="
  SERVICE_API_KEY: "tm_key_e61a9bd085e898e4f3c2cefd4e3b297fd78b76a297f0b766d597e8aa691bb1df"