apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation-service-prd
type: Opaque
stringData:
  REDIS_URL: "rediss://:F9l7mt7LubtaY9IOHq2xlY88Mx1uTwklGAzCaIK3JXs=@redis-togglemaster-fase-3.redis.cache.windows.net:6380"
  SERVICE_API_KEY: "tm_key_94b36dbeececcf6114df994d68ad108c406bae66628d2e4758d3ff7b5467ba6c"
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=satogglemasterf4;AccountKey=GKgCqEYv06etpWggCaDV02ubVMsS5jZj8k54Z1vXNURuRqMgr1p41hskmJkgg4Clhf+1wTxw+rBZ+AStPr56hw==;BlobEndpoint=https://satogglemasterf4.blob.core.windows.net/;FileEndpoint=https://satogglemasterf4.file.core.windows.net/;QueueEndpoint=https://satogglemasterf4.queue.core.windows.net/;TableEndpoint=https://satogglemasterf4.table.core.windows.net/"
  