apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: targeting-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AXMEDUSA/ToggleMaster-gitops
    targetRevision: main
    path: environments/prd/targeting-service
  destination:
    server: https://kubernetes.default.svc
    namespace: targeting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true