apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0b2dnbGVhY3JmYXM0LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJ0b2dnbGVhY3JmYXM0IiwicGFzc3dvcmQiOiI4eTV1cU1EOEJ0T0pMSTBJTlF4Qm5qUFV1RVlDMDV6WjBMOVY1MjYwSFVJSzBmazBYU3phSlFRSjk5Q0RBQ0hZSHY2RXFnN05BQUFDQVpDUkVUd1giLCJhdXRoIjoiZEc5bloyeGxZV055Wm1Gek5EbzRlVFYxY1UxRU9FSjBUMHBNU1RCSlRsRjRRbTVxVUZWMVJWbERNRFY2V2pCTU9WWTFNall3U0ZWSlN6Qm1hekJZVTNwaFNsRlJTams1UTBSQlEwaFpTSFkyUlhGbk4wNUJRVUZEUVZwRFVrVlVkMWc9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: acr-pull-secret
  namespace: auth-service-prd
type: kubernetes.io/dockerconfigjson
