apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0b2dnbGVhY3JmYXNlNC5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoidG9nZ2xlYWNyZmFzZTQiLCJwYXNzd29yZCI6Ijh5NXVxTUQ4QnRPSkxJMElOUXhCbmpQVXVFWUMwNXpaMEw5VjUyNjBIVUlLMGZrMFhTemFKUVFKOTlDREFDSFlIdjZFcWc3TkFBQUNBWkNSRVR3WCIsImF1dGgiOiJkRzluWjJ4bFlXTnlabUZ6WlRRNk9IazFkWEZOUkRoQ2RFOUtURWt3U1U1UmVFSnVhbEJWZFVWWlF6QTFlbG93VERsV05USTJNRWhWU1Vzd1ptc3dXRk42WVVwUlVVbzVPVU5FUVVOSVdVaDJOa1Z4WnpkT1FVRkJRMEZhUTFKRlZIZFkifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: acr-pull-secret
  namespace: auth-service-prd
type: kubernetes.io/dockerconfigjson
