apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: auth-service-prd
data:
  AUTH_PORT: "8001"
  DATABASE_URL: "postgresql://adminuser:T0ggl3M%40ster2026!@pg-auth-togglemaster-fase4.postgres.database.azure.com:5432/auth_db?sslmode=require"
  MASTER_KEY: "admin-secreto-123"
  POSTGRES_USER: "psqladmin"
  POSTGRES_DB: "auth_db"


