apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-service-prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: auth-service
          image: toggleacrfase4.azurecr.io/auth-service:00b9e34
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secrets
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "auth-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production,service.namespace=togglemaster"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "auth-service"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_TRACE_OTEL_ENABLED
              value: "false"
