apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-service-prd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: auth-service
          image: toggleacr.azurecr.io/auth-service:753079a
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secrets