configs:
  params:
    server:
      insecure: true

server:
  service:
    type: ClusterIP
  replicas: 1

controller:
  replicas: 1

repoServer:
  replicas: 1

redis:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false
