apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-service-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: analytics-service
          image: toggleacrfase4.azurecr.io/analytics-service:3fb7a6c
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secrets
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "analytics-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production,service.namespace=togglemaster"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "analytics-service"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_TRACE_DEBUG
              value: "false"
            - name: DD_TRACE_OTEL_ENABLED
              value: "false"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
