apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-service-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8005"
        prometheus.io/path: "/metrics"
      labels:
        app: analytics-service
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: analytics-service
          image: toggleacrfase4.azurecr.io/analytics-service:fb3d99b
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
