apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-service-prd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: analytics-service
          image: toggleacr.azurecr.io/analytics-service:a5c352b
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secrets
