apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics-service-prd
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=satogglemaster;AccountKey=DVjnc2ICnm0MODd+HMRTKI43PZyza937hYbs2t7N9ox0IY5RQ+VkABpRLfcsNhtY7pUSUrAS3yjh+AStxPYBUw==;EndpointSuffix=core.windows.net"
  AWS_SQS_URL: "https://satogglemaster.queue.core.windows.net/fila-togglemaster"
  AZURE_QUEUE_NAME: "fila-togglemaster"
  COSMOSDB_URL: "https://cosmosdb-togglemaster.documents.azure.com:443/" 
  COSMOSDB_KEY: "nLVLJJziKF3u5eY5WIzKyVS9LT7UHCKeppC1UgvceMeGlHhWdUJFXeuDDwFXhSaAGwwklILpIirIACDb6xUxUg==" 
  COSMOSDB_DATABASE: "cosmosdb-togglemaster"
  COSMOSDB_CONTAINER: "togglemaster"
  COSMOSDB_TABLE_NAME: "togglemaster"
  AZURE_TABLE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=cosmosdb-togglemaster;AccountKey=nLVLJJziKF3u5eY5WIzKyVS9LT7UHCKeppC1UgvceMeGlHhWdUJFXeuDDwFXhSaAGwwklILpIirIACDb6xUxUg==;TableEndpoint=https://cosmosdb-togglemaster.table.cosmos.azure.com:443/;"

