apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics-service-prd
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_ACCESS_KEY"
  AWS_SESSION_TOKEN: "YOUR_SESSION_TOKEN"
  AWS_SQS_URL: "YOUR_SQS_URL"
  AWS_REGION: "us-east-1"