apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics-service-prd
type: Opaque
stringData:
  AWS_SQS_URL: "https://satogglemaster.queue.core.windows.net/fila-togglemaster"
  AZURE_QUEUE_NAME: "fila-togglemaster"
  COSMOSDB_URL: "https://cosmosdb-togglemaster.table.cosmos.azure.com:443"
  COSMOSDB_KEY: "WCa7sCmMUWOpr584yfu4gSQNRl9d2udfi7hh5dEV2ZLbcOXUdtnfdVvDIi2u9PyanwoZF8qQxKTuACDbcnoaRQ=="
  COSMOSDB_DATABASE: "cosmosdb-togglemaster"
  COSMOSDB_CONTAINER: "togglemaster"
