apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: analytics-service-prd
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
      name: http


#kubectl run -it --rm curl --image=curlimages/curl -n analytics-service-prd --restart=Never -- curl http://analytics-service.analytics-service-prd.svc.cluster.local:8005/health
