apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AXMEDUSA/ToggleMaster-gitops.git
    targetRevision: main
    path: auth-service

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true